name: occult
description: A framework for a madman
repository: https://github.com/ArcaneArts/Occult
version: 0.0.1-dev.8
environment:
  sdk: ^3.6.1
executables: 
  occult: 
dependencies:
  cli_annotations: ^0.1.0-dev.6
  args: ^2.6.0
  dart_mappable: ^4.3.1
  interact: ^2.2.0
  tint: ^2.0.1
  yaml_edit: ^2.2.2
  yaml: ^3.1.3
  archive: ^4.0.2
  path: ^1.9.1
  xml: ^6.5.0
dev_dependencies:
  build_runner: ^2.4.15
  cli_gen: ^0.1.0-dev.6
  dart_mappable_builder: ^4.3.1+1
scripts: 
  build_runner: dart run build_runner build --delete-conflicting-outputs